### ISSUE TITLE
qxldod driver in 134 is not signed

### ISSUE THREAD

**Issue by gschukin** [crobinso/virtio-win-pkg-scripts#11]
qxl-wddm-dod driver for Win2012R2 shipped with 134 drivers iso is not signed while the driver shipped with 133-1 iso was signed properly.

**Comment by crobinso** [comment]
Thanks for the report. I'm trying to figure out if I screwed up the packaging, or if the source archives are wrong. Can you grab the -Signed archive here and see if those drivers work for?

https://www.spice-space.org/download/windows/qxl-wddm-dod/qxl-wddm-dod-0.16/

**Comment by gschukin** [comment]
Hi @crobinso 
My bad I didn't check it first

The results are:
spice-qxl-wddm-dod-0.16-Signed.zip - is actually **not** signed
spice-qxl-wddm-dod-0.16-Unsigned.zip - is actually signed

**Comment by crobinso** [comment]
Thanks, the latest build should have drivers swapped, please let me know if they work for you. I'm following up with spice-space people to figure out what's going on with those archives

**Comment by ybendito** [comment]
I've checked these drivers. Results are (as expected):
spice-qxl-wddm-dod-0.16-Unsigned.zip - signed by Red Hat only
spice-qxl-wddm-dod-0.16-Signed.zip - CAT signed by Microsoft, SYS signed by both Microsoft and Red Hat

**Comment by gschukin** [comment]
@ybendito If I try to install spice-qxl-wddm-dod-0.16-Signed.zip via update driver in device manager
installation wizard complains that driver is not signed. Also it also noted that driver is not signed in device properties -> driver tab

spice-qxl-wddm-dod-0.16-Unsigned.zip - wizard only asks if I trust "Red Hat Inc.", in device properties -> driver tab it also noted that the driver is signed by Red Hat Inc.

**Comment by ybendito** [comment]
On which operating system you try to install the 'signed' driver?

**Comment by gschukin** [comment]
Windows Server 2012R2

**Comment by ybendito** [comment]
Use 'unsigned' package. On regular Win10 both packages work, on Win10 with secured boot only 'signed' one works. On Pre-Win10 systems the 'signed' package was not tested yet (as it is not intended to be used on them). Thank you for your feedback.

**Comment by gschukin** [comment]
Maybe it will be better to rename archives as it is really confusing right now.
