### ISSUE TITLE
Balloon device is installed, but blnsrv.exe is missing a .msi to install and create the service

### ISSUE THREAD

**Issue by stumbaumr** [crobinso/virtio-win-pkg-scripts#18]
Hi,

you provide a .MSI for the guest-agent, but not for the Balloon Service.

If someone like the chocolatey package maintainer just loops over the directory structure and installs all the .INF files he will miss out on the blnsrv.exe.

Could you provide a proper .MSI for the blnsrv.exe please.

Thanks
Rainer

**Comment by crobinso** [comment]
There is work right now to create a unified msi installer for all the drivers and agents, and get it on the public virtio-win iso. The installer code is here: https://github.com/virtio-win/virtio-win-guest-tools-installer

When that is integrated it will kinda cover this. But if you still specifically want a blnsrv.msi you'll need to request that the kvm-windows-guest-drivers build system outputs one, so you'll want to file a request there: https://github.com/virtio-win/kvm-guest-drivers-windows
