### ISSUE TITLE
I did not understand how it works.

### ISSUE THREAD

**Issue by morphinz** [crobinso/virtio-win-pkg-scripts#8]
Hello.

Can you please give more information about usage? Maybe an example of builted directory?
Readme document not user friendly.
```
Morphin:~/Documents/iso:./make-driver-dir.py \
> ../iso/kvm-guest-drivers-windows-master/
ERROR: driver=qxldod ostuple=Win8/x64 not found in input=/home/morphin/Documents/iso/kvm-guest-drivers-windows-master/
```
I don't have qxldod drivers and i dont need that.

**Comment by crobinso** [comment]
Unfortunately these scripts aren't really general purpose yet, and depend on internal redhat build output. That output can be published but I haven't wired up my scripts to do so yet in an automated fashion.

If you don't want qxldod in your iso you'll need to manually edit the scripts to remove those parts.
